os: osx

language: objective-c

git:
  depth: 5

env:
  global:
    - secure: "onieVGY07aLfwQPw8T4Gg7TnBfvd7GWhZ17XsT0jdH5JCkcIXkVsx8pirH76zj27X3tIE2v1ZeIzK3v6x186p0Cd3wRpODKDlqTxfi6CQa0sazIORhrs15mTABrxuPSJ9kB5+5RB9UHvlpKS2oMvs1HBf88SPZUE7wUuQnA2Zne9jvIuwPxMOwwbYh5VAQZTP3EAhhAhzjpey+GLyzJn5tY+J5j9RHhVmtaoNtpr7nlK3D+pfQ8bjzLFuefap2pwZvWfvbXGHG2Kudg3BK7649oEtZsjIfxclalYaYaiO7vbisVxR1hDKjsGUHkVfFXHvb/Dpr6w+K0KMVYm/LqM6ZW0PBXn7r2pf0j3rlTDea7r7zCz0PObeW7faZO/9tW6fTzX+HjAKlBF+LL9loRBxYv6JcRFL+mNzRBFQLAdClRxXqoAD9Whja6FJF38ujQWi0VLR8sSSamP1Jceu8rDj08pezHy4HbofDwyEnBnQVDc4YcLQfB8au8jJIPLMkKCp9vxZfIDhqh8vLT5pJi18VJopO94ulVzxk1Y/AEKOQKYOmpg5qy34SWSFe7kY9dmNjla65BcyV8PMzzCNuPxaAn3BNXSGWF28CEX1dgl3kc8RZCMlRFm7HP5XbZV9oE/7h0IyL1CJuczEdmyE/HmXuSI9nnz1OveAS7dYTZ/stU="
  matrix:
    - NODE_VERSION="0.10.40"
    - NODE_VERSION="0.12.7"
    - NODE_VERSION="4.2.3"
    - NODE_VERSION="5.1.1"

before_install:
  - brew update
  - brew install ffmpeg --with-libvpx --with-libvorbis

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node -v
  - npm -v
  - npm install

script:
  - mkdir /Users/travis/build/renambot-uic/Build
  - cd ..
  - tar czf /Users/travis/build/renambot-uic/Build/node-demux_mac_${NODE_VERSION}.tar.gz node-demux
  - cd node-demux
  - mv /Users/travis/build/renambot-uic/Build/node-demux_mac_${NODE_VERSION}.tar.gz .
  - curl --insecure --progress-bar --location --fail --user "renambot:$BITBUCKET_PASSWORD" --form files=@"node-demux_mac_${NODE_VERSION}.tar.gz" "https://api.bitbucket.org/2.0/repositories/sage2/sage2/downloads/"
  - ls -a

