version: 1.0.{build}

branches:
  only:
  - master

configuration: Release
platform: x64
#clone_depth: 5
# specific to github and bitbucket: get a ZIP file using REST API
shallow_clone: true


init:
- curl -LsSO http://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-3.0.1-win64-dev.7z
- 7z x ffmpeg-3.0.1-win64-dev.7z -o.
- mkdir C:\Dev\
- mkdir C:\Dev\ffmpeg-win64-dev
- move ffmpeg-3.0.1-win64-dev\lib C:\Dev\ffmpeg-win64-dev
- move ffmpeg-3.0.1-win64-dev\include C:\Dev\ffmpeg-win64-dev
- del /Q *.7z
- rmdir /Q /S ffmpeg-3.0.1-win64-dev
- dir C:\Dev
- dir C:\Dev\ffmpeg-win64-dev\include
- dir C:\Dev\ffmpeg-win64-dev\lib
- ps: Get-NodeJsLatestBuild 6.0

environment:
  BITBUCKET_PASSWORD:
    secure: vqHQj3wH0DrNMmmeflA6Nw==
  matrix:
  - nodejs_version: 0.10.44
  - nodejs_version: 0.12.13
  - nodejs_version: 4.4.2
  - nodejs_version: 5.10.1
  - nodejs_version: 6.0.0
  - nodejs_version: 7.0.0

install:
- ps: >-
    Install-Product node $env:nodejs_version x64

    npm -v

    node -v

    npm install --production --msvs_version=2013

build:
  parallel: true
  verbosity: minimal

after_build:
- curl -LsSO http://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-3.0.1-win64-shared.7z
- 7z x ffmpeg-3.0.1-win64-shared.7z -o.
- move ffmpeg-3.0.1-win64-shared\bin\* build\Release
- rmdir /Q /S ffmpeg-3.0.1-win64-shared
- del /Q *.7z
- mkdir C:\Build\
- 7z a -ttar C:\Build\node-demux_win_%nodejs_version%.tar C:\projects\node-demux\
- 7z a -tgzip C:\Build\node-demux_win_%nodejs_version%.tar.gz C:\Build\node-demux_win_%nodejs_version%.tar
- move C:\Build\node-demux_win_%nodejs_version%.tar.gz C:\projects\node-demux
- curl --insecure --progress-bar --location --fail --user "renambot:%BITBUCKET_PASSWORD%" --form files=@"node-demux_win_%nodejs_version%.tar.gz" "https://api.bitbucket.org/2.0/repositories/sage2/binaries/downloads/"
- dir

test: off
